AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  Database:
    Type: AWS::Serverless::Application
    Properties:
      Location: model/templates/database.yaml
      Parameters:
        Environment: !Ref Environment

  Lambda:
    Type: AWS::Serverless::Application
    Properties:
      Location: model/templates/lambda.yaml
      Parameters:
        Environment: !Ref Environment
        UsersTableArn: !GetAtt Database.Outputs.UsersTableArn
        UsersTableName: !GetAtt Database.Outputs.UsersTableName

  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: model/templates/api.yaml
      Parameters:
        Environment: !Ref Environment
        UsersLambdaArn: !GetAtt Lambda.Outputs.UsersFunctionArn
        UsersTableArn: !GetAtt Database.Outputs.UsersTableArn
        UsersTableName: !GetAtt Database.Outputs.UsersTableName

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !GetAtt Api.Outputs.ApiEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-${Environment}-ApiEndpoint'
  ApiId:
    Description: API Gateway ID
    Value: !GetAtt Api.Outputs.ApiId
    Export:
      Name: !Sub '${AWS::StackName}-${Environment}-ApiId'
  UsersTableName:
    Description: DynamoDB table name
    Value: !GetAtt Database.Outputs.UsersTableName
